spring.application.name=meetapp
server.port=${PORT:8083}

# Database Configuration (use environment variables for production)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.web.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration (use environment variables for production)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:ashishraj0609@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vngnptjjskroziqd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration (use environment variable for production)
jwt.secret=${JWT_SECRET:my-super-secret-key-my-super-secret-key-256bit}
jwt.expiration=86400000

